pipeline{
    agent any
    options{
        timeout(5)
    }
    stages{
                stage("1 check status"){
            steps{
                sh 'echo hello'
                echo "i love aws"

            }
            
        }

        
   
    }
    
}
